version: '3.5'

services:
    traffmonetizer:
        image: traffmonetizer/cli_v2
        restart: always
        command: start accept --token 9KB5/Y0XfS9LT7sOZm4hwMB4BrA2DmmhnUynd/3nD+Y= --net host
